# SETUP

In [1]:
from google.colab import drive
drive.mount('/content/drive')

!pip install -q transformers datasets torch scikit-learn accelerate evaluate tqdm

import json
import pandas as pd
import numpy as np
import torch
from pathlib import Path
from datetime import datetime
from tqdm import tqdm
from sklearn.metrics import f1_score, precision_score, recall_score
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
from datasets import Dataset
from huggingface_hub import login

login(token="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")

BASE_DIR = Path("/content/drive/MyDrive/mental_health_research_V2")
DATA_DIR = BASE_DIR / "data" / "processed" / "go_emotions"
MODEL_DIR = BASE_DIR / "models" / "mental_bert_goemotions"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Mounted at /content/drive
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.7 MB/s eta 0:00:00
Device: cuda

# DATA PREPARATION

In [2]:
# Load dataset
data_files = sorted(DATA_DIR.glob("go_emotions_raw_*.json"))
data_file = data_files[-1]

with open(data_file, 'r') as f:
    data = json.load(f)

df = pd.DataFrame(data)
print(f"Loaded: {data_file.name}")
print(f"Total samples: {len(df):,}")
print(f"\nSplit distribution:")
print(df['split'].value_counts())

Loaded: go_emotions_raw_20251118_154517.json
Total samples: 57,732

Split distribution:
split
train         46185
test           5774
validation     5773
Name: count, dtype: int64

In [3]:
# GoEmotions has 28 emotion labels (27 emotions + 1 neutral)
emotion_labels = [
    'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
    'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment',
    'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness',
    'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral'
]

num_labels = len(emotion_labels)
print(f"Number of emotion labels: {num_labels}")
print(f"Labels: {emotion_labels}")

Number of emotion labels: 28
Labels: ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']

In [4]:
def labels_to_multihot(labels, num_labels=28):
    multihot = np.zeros(num_labels, dtype=np.float32)
    for label in labels:
        multihot[label] = 1.0
    return multihot

df['labels_multihot'] = df['labels'].apply(lambda x: labels_to_multihot(x, num_labels))

In [5]:
# Split data
train_df = df[df['split'] == 'train'].reset_index(drop=True)
val_df = df[df['split'] == 'validation'].reset_index(drop=True)
test_df = df[df['split'] == 'test'].reset_index(drop=True)

print(f"Train: {len(train_df):,}")
print(f"Validation: {len(val_df):,}")
print(f"Test: {len(test_df):,}")

Train: 46,185
Validation: 5,773
Test: 5,774

In [6]:
model_name = "mental/mental-bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/321 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [7]:
# Tokenize datasets
def tokenize_function(examples):
    return tokenizer(
        examples['text'],
        truncation=True,
        padding='max_length',
        max_length=128
    )

# Convert to Dataset format
train_dataset = Dataset.from_pandas(train_df[['text', 'labels_multihot']])
val_dataset = Dataset.from_pandas(val_df[['text', 'labels_multihot']])
test_dataset = Dataset.from_pandas(test_df[['text', 'labels_multihot']])

# Tokenize
train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# Rename labels
train_dataset = train_dataset.rename_column('labels_multihot', 'labels')
val_dataset = val_dataset.rename_column('labels_multihot', 'labels')
test_dataset = test_dataset.rename_column('labels_multihot', 'labels')

# Set format
train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
val_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])

print(f"Datasets ready - Train: {len(train_dataset)}, Val: {len(val_dataset)}, Test: {len(test_dataset)}")

Map:   0%|          | 0/46185 [00:00<?, ? examples/s]

Map:   0%|          | 0/5773 [00:00<?, ? examples/s]

Map:   0%|          | 0/5774 [00:00<?, ? examples/s]

Datasets ready - Train: 46185, Val: 5773, Test: 5774

# MODEL CONFIGURATION

In [8]:
# Load model
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    problem_type="multi_label_classification"
)

model.to(device)
print(f"Model loaded: {model_name}")
print(f"Parameters: {model.num_parameters():,}")

config.json:   0%|          | 0.00/639 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model loaded: mental/mental-bert-base-uncased
Parameters: 109,503,772

In [9]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(predictions))
    y_pred = (probs > 0.5).int().numpy()
    y_true = labels

    return {
        'f1_micro': f1_score(y_true, y_pred, average='micro'),
        'f1_macro': f1_score(y_true, y_pred, average='macro'),
        'precision': precision_score(y_true, y_pred, average='micro'),
        'recall': recall_score(y_true, y_pred, average='micro')
    }

In [10]:
# Load class weights
weights_file = DATA_DIR / "class_weights.json"
with open(weights_file, 'r') as f:
    class_weights_dict = json.load(f)

pos_weight = torch.tensor([class_weights_dict[label] for label in emotion_labels], dtype=torch.float32).to(device)

# HYPERPARAMETER OPTIMIZATION

In [11]:
!pip install -q optuna

import optuna

def objective(trial):
    lr = trial.suggest_float('learning_rate', 1e-5, 5e-5, log=True)
    batch_size = trial.suggest_categorical('batch_size', [128, 256, 512])
    gamma = trial.suggest_float('focal_gamma', 1.0, 2.5)
    alpha = trial.suggest_float('focal_alpha', 0.25, 1.0)

    trial_args = TrainingArguments(
        output_dir=str(MODEL_DIR / f"trial_{trial.number}"),
        num_train_epochs=3,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=512,
        learning_rate=lr,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="no",
        warmup_steps=500,
        fp16=True,
        report_to="none"
    )

    trial_pos_weight = pos_weight.clone()

    class TrialFocalLoss(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.alpha = alpha
            self.gamma = gamma

        def forward(self, inputs, targets):
            bce_loss = torch.nn.functional.binary_cross_entropy_with_logits(
                inputs, targets, pos_weight=trial_pos_weight, reduction='none'
            )
            probs = torch.sigmoid(inputs)
            pt = torch.where(targets == 1, probs, 1 - probs)
            focal_weight = (1 - pt) ** self.gamma
            loss = self.alpha * focal_weight * bce_loss
            return loss.mean()

    class TrialTrainer(Trainer):
        def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
            labels = inputs.pop("labels")
            outputs = model(**inputs)
            logits = outputs.logits
            loss = TrialFocalLoss()(logits, labels)
            return (loss, outputs) if return_outputs else loss

    trial_model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
        problem_type="multi_label_classification"
    ).to(device)

    trainer = TrialTrainer(
        model=trial_model,
        args=trial_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics
    )

    trainer.train()
    eval_result = trainer.evaluate()

    del trial_model
    torch.cuda.empty_cache()

    return eval_result['eval_f1_macro']

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

print(f"\nBest F1-macro: {study.best_value:.4f}")
print(f"Best hyperparameters:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

best_lr = study.best_params['learning_rate']
best_batch_size = study.best_params['batch_size']
best_gamma = study.best_params['focal_gamma']
best_alpha = study.best_params['focal_alpha']

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 31.5 MB/s eta 0:00:00

[I 2025-11-18 15:47:02,784] A new study created in memory with name: no-name-a217efdd-3ef0-4f1e-b5fb-8d0893557fad
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 15:48:40,680] Trial 0 finished with value: 0.22690196609688368 and parameters: {'learning_rate': 3.275613793254354e-05, 'batch_size': 256, 'focal_gamma': 2.1940663145874773, 'focal_alpha': 0.33174434664874297}. Best is trial 0 with value: 0.22690196609688368.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 15:50:27,910] Trial 1 finished with value: 0.28718282120283073 and parameters: {'learning_rate': 4.529319023022981e-05, 'batch_size': 128, 'focal_gamma': 1.68425818079851, 'focal_alpha': 0.5113417940936987}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2025-11-18 15:52:04,830] Trial 2 finished with value: 0.0 and parameters: {'learning_rate': 1.2569069137451048e-05, 'batch_size': 256, 'focal_gamma': 1.4499361998869493, 'focal_alpha': 0.6184053871363893}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 15:53:41,683] Trial 3 finished with value: 0.12777185583415845 and parameters: {'learning_rate': 2.1450691438170225e-05, 'batch_size': 256, 'focal_gamma': 1.7155987199859482, 'focal_alpha': 0.2630742513697481}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 15:55:29,168] Trial 4 finished with value: 0.2438242919771272 and parameters: {'learning_rate': 2.7692985938148613e-05, 'batch_size': 128, 'focal_gamma': 1.4836429112542024, 'focal_alpha': 0.7308323267555299}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 15:57:06,169] Trial 5 finished with value: 0.2234937315649034 and parameters: {'learning_rate': 4.522559326812028e-05, 'batch_size': 256, 'focal_gamma': 1.4753101378638265, 'focal_alpha': 0.3283314067267227}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 15:58:43,226] Trial 6 finished with value: 0.03893358520188615 and parameters: {'learning_rate': 1.2731061842794265e-05, 'batch_size': 256, 'focal_gamma': 1.95001807807402, 'focal_alpha': 0.6624772431726214}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2025-11-18 16:00:14,063] Trial 7 finished with value: 0.0 and parameters: {'learning_rate': 1.0254256320605808e-05, 'batch_size': 512, 'focal_gamma': 2.4706246513952532, 'focal_alpha': 0.7539828920107715}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:01:45,058] Trial 8 finished with value: 0.03358257903712449 and parameters: {'learning_rate': 4.0739132334168015e-05, 'batch_size': 512, 'focal_gamma': 2.2507533691304795, 'focal_alpha': 0.7169433813968592}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:03:32,549] Trial 9 finished with value: 0.22326825458973087 and parameters: {'learning_rate': 1.804943380300894e-05, 'batch_size': 128, 'focal_gamma': 2.2180213845835333, 'focal_alpha': 0.4321587159166738}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:05:19,917] Trial 10 finished with value: 0.2284154478568244 and parameters: {'learning_rate': 3.26730702668795e-05, 'batch_size': 128, 'focal_gamma': 1.01075795457044, 'focal_alpha': 0.9956205985805779}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:07:07,180] Trial 11 finished with value: 0.2496400308405295 and parameters: {'learning_rate': 3.1086133245521896e-05, 'batch_size': 128, 'focal_gamma': 1.377228773054194, 'focal_alpha': 0.5212926791280518}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:08:54,527] Trial 12 finished with value: 0.2664778207658153 and parameters: {'learning_rate': 4.623901905686887e-05, 'batch_size': 128, 'focal_gamma': 1.0849651950925168, 'focal_alpha': 0.5079207211910228}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:10:41,899] Trial 13 finished with value: 0.2651107918383405 and parameters: {'learning_rate': 4.807853828440947e-05, 'batch_size': 128, 'focal_gamma': 1.0683776355854693, 'focal_alpha': 0.5138710398297482}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:12:29,214] Trial 14 finished with value: 0.2563666091034641 and parameters: {'learning_rate': 3.9094955451797766e-05, 'batch_size': 128, 'focal_gamma': 1.228680916393069, 'focal_alpha': 0.5039061500868101}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:14:16,531] Trial 15 finished with value: 0.23711370148405359 and parameters: {'learning_rate': 2.409843856469966e-05, 'batch_size': 128, 'focal_gamma': 1.7157208702361, 'focal_alpha': 0.8336436150008747}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:16:03,848] Trial 16 finished with value: 0.2805749365797674 and parameters: {'learning_rate': 3.82504665237557e-05, 'batch_size': 128, 'focal_gamma': 1.8853930046222673, 'focal_alpha': 0.4263920212007004}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:17:34,809] Trial 17 finished with value: 0.0009306654257794323 and parameters: {'learning_rate': 3.703403301533794e-05, 'batch_size': 512, 'focal_gamma': 1.955269874804639, 'focal_alpha': 0.4081536551820191}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:19:22,041] Trial 18 finished with value: 0.22437046105736363 and parameters: {'learning_rate': 2.0188252336036523e-05, 'batch_size': 128, 'focal_gamma': 1.890481671365057, 'focal_alpha': 0.6072261630040918}. Best is trial 1 with value: 0.28718282120283073.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at mental/mental-bert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:21:09,276] Trial 19 finished with value: 0.24298503067150062 and parameters: {'learning_rate': 2.6716999953721063e-05, 'batch_size': 128, 'focal_gamma': 1.6297555132355706, 'focal_alpha': 0.4184978733287154}. Best is trial 1 with value: 0.28718282120283073.

Best F1-macro: 0.2872
Best hyperparameters:
  learning_rate: 4.529319023022981e-05
  batch_size: 128
  focal_gamma: 1.68425818079851
  focal_alpha: 0.5113417940936987

# TRAINING

In [12]:
# Create final training args with optimized hyperparameters
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_dir = MODEL_DIR / f"checkpoint_{timestamp}"
final_model_dir = MODEL_DIR / f"mental_bert_finetuned_{timestamp}"

final_training_args = TrainingArguments(
    output_dir=str(output_dir),
    num_train_epochs=3,
    per_device_train_batch_size=best_batch_size if 'best_batch_size' in dir() else 256,
    per_device_eval_batch_size=512,
    learning_rate=best_lr if 'best_lr' in dir() else 2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_micro",
    logging_steps=100,
    warmup_steps=500,
    fp16=True,
    save_total_limit=2,
    report_to="none"
)

# Initialize Trainer with optimized Focal Loss
final_alpha = best_alpha if 'best_alpha' in dir() else 1.0
final_gamma = best_gamma if 'best_gamma' in dir() else 2.0

class FinalFocalLoss(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.alpha = final_alpha
        self.gamma = final_gamma
        self.pos_weight = pos_weight

    def forward(self, inputs, targets):
        bce_loss = torch.nn.functional.binary_cross_entropy_with_logits(
            inputs, targets, pos_weight=self.pos_weight, reduction='none'
        )
        probs = torch.sigmoid(inputs)
        pt = torch.where(targets == 1, probs, 1 - probs)
        focal_weight = (1 - pt) ** self.gamma
        loss = self.alpha * focal_weight * bce_loss
        return loss.mean()

class FinalTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss = FinalFocalLoss()(logits, labels)
        return (loss, outputs) if return_outputs else loss

trainer = FinalTrainer(
    model=model,
    args=final_training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

/tmp/ipython-input-3596736075.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `FinalTrainer.__init__`. Use `processing_class` instead.
  trainer = FinalTrainer(

In [13]:
# Train with optimized hyperparameters
train_result = trainer.train()

print(f"\nTraining complete - Time: {train_result.metrics['train_runtime']:.2f}s")

Training complete - Time: 129.67s

# EVALUATION

In [14]:
# Evaluate on validation
val_results = trainer.evaluate()

print("Validation Results:")
for key, value in val_results.items():
    print(f"{key}: {value:.4f}")

Validation Results:
eval_loss: 0.0192
eval_f1_micro: 0.2728
eval_f1_macro: 0.2799
eval_precision: 0.5773
eval_recall: 0.1786
eval_runtime: 1.8777
eval_samples_per_second: 3074.4270
eval_steps_per_second: 6.3910
epoch: 3.0000

In [15]:
# Evaluate on test
test_results = trainer.evaluate(test_dataset)

print("Test Results:")
for key, value in test_results.items():
    print(f"{key}: {value:.4f}")

Test Results:
eval_loss: 0.0192
eval_f1_micro: 0.2701
eval_f1_macro: 0.2740
eval_precision: 0.5814
eval_recall: 0.1759
eval_runtime: 1.8846
eval_samples_per_second: 3063.7310
eval_steps_per_second: 6.3670
epoch: 3.0000

In [16]:
# Per-emotion scores with fixed threshold (0.5)
test_predictions = trainer.predict(test_dataset)
sigmoid = torch.nn.Sigmoid()
probs = sigmoid(torch.Tensor(test_predictions.predictions))
pred_labels = (probs > 0.5).int().numpy()

print("\nPer-Emotion F1 Scores (Fixed Threshold 0.5):")
for i, emotion in enumerate(emotion_labels):
    f1 = f1_score(test_predictions.label_ids[:, i], pred_labels[:, i], zero_division=0)
    print(f"{emotion:15s}: {f1:.4f}")

Per-Emotion F1 Scores (Fixed Threshold 0.5):
admiration     : 0.4306
amusement      : 0.5647
anger          : 0.2482
annoyance      : 0.0000
approval       : 0.0237
caring         : 0.2455
confusion      : 0.1841
curiosity      : 0.1447
desire         : 0.2994
disappointment : 0.0227
disapproval    : 0.0185
disgust        : 0.2626
embarrassment  : 0.2772
excitement     : 0.1856
fear           : 0.4607
gratitude      : 0.8333
grief          : 0.2353
joy            : 0.2780
love           : 0.6695
nervousness    : 0.2830
optimism       : 0.3119
pride          : 0.2154
realization    : 0.0000
relief         : 0.2162
remorse        : 0.4968
sadness        : 0.3280
surprise       : 0.4373
neutral        : 0.0000

# THRESHOLD OPTIMIZATION

In [17]:
# Get validation predictions (probabilities)
val_predictions = trainer.predict(val_dataset)
val_probas = torch.sigmoid(torch.Tensor(val_predictions.predictions)).numpy()
val_labels = val_predictions.label_ids

print(f"Validation probabilities shape: {val_probas.shape}")
print(f"Validation labels shape: {val_labels.shape}")

Validation probabilities shape: (5773, 28)
Validation labels shape: (5773, 28)

In [18]:
# Grid search for optimal thresholds per emotion
threshold_results = {}

print("Running grid search for optimal thresholds...")
for t in tqdm(range(5, 100, 5), desc="Testing thresholds"):
    threshold = t / 100
    threshold_results[threshold] = []

    for label_idx, emotion in enumerate(emotion_labels):
        y_true = val_labels[:, label_idx]
        y_pred = (val_probas[:, label_idx] > threshold).astype(int)

        f1 = f1_score(y_true, y_pred, zero_division=0)
        precision = precision_score(y_true, y_pred, zero_division=0)
        recall = recall_score(y_true, y_pred, zero_division=0)
        support = y_true.sum()

        threshold_results[threshold].append({
            'emotion': emotion,
            'threshold': threshold,
            'f1': f1,
            'precision': precision,
            'recall': recall,
            'support': support
        })

print(f"Grid search complete! Tested {len(threshold_results)} thresholds for {len(emotion_labels)} emotions.")

Running grid search for optimal thresholds...

Testing thresholds: 100%|██████████| 19/19 [00:03<00:00,  4.99it/s]

Grid search complete! Tested 19 thresholds for 28 emotions.

In [19]:
# Find best threshold for each emotion
best_thresholds = {}
best_metrics = []

for emotion in emotion_labels:
    best_f1 = -1
    best_result = None

    for threshold, results in threshold_results.items():
        for result in results:
            if result['emotion'] == emotion and result['f1'] > best_f1:
                best_f1 = result['f1']
                best_result = result

    best_thresholds[emotion] = best_result['threshold']
    best_metrics.append(best_result)

# Display optimal thresholds
print("Optimal Thresholds per Emotion:")
print("=" * 60)
for metric in sorted(best_metrics, key=lambda x: x['support'], reverse=True):
    print(f"{metric['emotion']:15s} | Threshold: {metric['threshold']:.2f} | F1: {metric['f1']:.4f} | Support: {int(metric['support']):>4}")

print(f"\nAverage optimal threshold: {np.mean(list(best_thresholds.values())):.3f}")

Optimal Thresholds per Emotion:
============================================================
neutral         | Threshold: 0.20 | F1: 0.5423 | Support: 1547
approval        | Threshold: 0.25 | F1: 0.2731 | Support:  475
admiration      | Threshold: 0.35 | F1: 0.5813 | Support:  458
annoyance       | Threshold: 0.30 | F1: 0.2905 | Support:  352
disapproval     | Threshold: 0.30 | F1: 0.3284 | Support:  315
curiosity       | Threshold: 0.30 | F1: 0.5063 | Support:  311
gratitude       | Threshold: 0.45 | F1: 0.8021 | Support:  302
amusement       | Threshold: 0.40 | F1: 0.6615 | Support:  287
optimism        | Threshold: 0.35 | F1: 0.4650 | Support:  274
realization     | Threshold: 0.30 | F1: 0.1931 | Support:  234
anger           | Threshold: 0.40 | F1: 0.4252 | Support:  231
joy             | Threshold: 0.40 | F1: 0.4495 | Support:  223
love            | Threshold: 0.40 | F1: 0.6457 | Support:  220
disappointment  | Threshold: 0.35 | F1: 0.2571 | Support:  208
confusion       | Threshold: 0.35 | F1: 0.3588 | Support:  190
sadness         | Threshold: 0.40 | F1: 0.4121 | Support:  185
excitement      | Threshold: 0.30 | F1: 0.2546 | Support:  156
surprise        | Threshold: 0.50 | F1: 0.4644 | Support:  154
caring          | Threshold: 0.35 | F1: 0.3212 | Support:  153
disgust         | Threshold: 0.45 | F1: 0.2905 | Support:  135
desire          | Threshold: 0.50 | F1: 0.3735 | Support:   97
fear            | Threshold: 0.50 | F1: 0.4592 | Support:   87
remorse         | Threshold: 0.50 | F1: 0.6321 | Support:   87
embarrassment   | Threshold: 0.50 | F1: 0.3486 | Support:   71
nervousness     | Threshold: 0.50 | F1: 0.2778 | Support:   51
relief          | Threshold: 0.55 | F1: 0.2817 | Support:   44
pride           | Threshold: 0.40 | F1: 0.1277 | Support:   35
grief           | Threshold: 0.60 | F1: 0.3030 | Support:   15

Average optimal threshold: 0.398

In [20]:
# Save optimal thresholds
final_model_dir.mkdir(parents=True, exist_ok=True)
thresholds_file = final_model_dir / "optimal_thresholds.json"
with open(thresholds_file, 'w') as f:
    json.dump(best_thresholds, f, indent=2)

print(f"Optimal thresholds saved to: {thresholds_file}")

Optimal thresholds saved to: /content/drive/MyDrive/mental_health_research_V2/models/mental_bert_goemotions/mental_bert_finetuned_20251118_162109/optimal_thresholds.json

In [21]:
# Evaluate on test set with optimized thresholds
test_probas = torch.sigmoid(torch.Tensor(test_predictions.predictions)).numpy()
test_labels = test_predictions.label_ids

# Apply per-emotion optimal thresholds
test_preds_optimized = np.zeros_like(test_probas, dtype=int)
for label_idx, emotion in enumerate(emotion_labels):
    threshold = best_thresholds[emotion]
    test_preds_optimized[:, label_idx] = (test_probas[:, label_idx] > threshold).astype(int)

# Calculate metrics with optimized thresholds
f1_macro_optimized = f1_score(test_labels, test_preds_optimized, average='macro', zero_division=0)
f1_micro_optimized = f1_score(test_labels, test_preds_optimized, average='micro', zero_division=0)
precision_optimized = precision_score(test_labels, test_preds_optimized, average='macro', zero_division=0)
recall_optimized = recall_score(test_labels, test_preds_optimized, average='macro', zero_division=0)

print("Test Results with Optimized Thresholds:")
print("=" * 60)
print(f"F1-macro:  {f1_macro_optimized:.4f}")
print(f"F1-micro:  {f1_micro_optimized:.4f}")
print(f"Precision: {precision_optimized:.4f}")
print(f"Recall:    {recall_optimized:.4f}")

Test Results with Optimized Thresholds:
============================================================
F1-macro:  0.3818
F1-micro:  0.4456
Precision: 0.3677
Recall:    0.4212

In [22]:
# Per-emotion scores with optimized thresholds
print("\nPer-Emotion F1 Scores (Optimized Thresholds):")
print("=" * 80)
print(f"{'Emotion':<15} | {'Threshold':>9} | {'F1':>8} | {'Precision':>9} | {'Recall':>9} | {'Support':>7}")
print("-" * 80)

optimized_emotion_metrics = []
for i, emotion in enumerate(emotion_labels):
    y_true = test_labels[:, i]
    y_pred = test_preds_optimized[:, i]

    f1 = f1_score(y_true, y_pred, zero_division=0)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    support = y_true.sum()
    threshold = best_thresholds[emotion]

    optimized_emotion_metrics.append({
        'emotion': emotion,
        'threshold': threshold,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'support': support
    })

    print(f"{emotion:<15} | {threshold:>9.2f} | {f1:>8.4f} | {precision:>9.4f} | {recall:>9.4f} | {int(support):>7}")

print("=" * 80)

Per-Emotion F1 Scores (Optimized Thresholds):
================================================================================
Emotion         | Threshold |       F1 | Precision |    Recall | Support
--------------------------------------------------------------------------------
admiration      |      0.35 |   0.5691 |    0.5821 |    0.5567 |     503
amusement       |      0.40 |   0.6164 |    0.5222 |    0.7520 |     250
anger           |      0.40 |   0.3607 |    0.3615 |    0.3598 |     214
annoyance       |      0.30 |   0.2668 |    0.2260 |    0.3256 |     347
approval        |      0.25 |   0.2878 |    0.2425 |    0.3540 |     500
caring          |      0.35 |   0.3747 |    0.3318 |    0.4303 |     165
confusion       |      0.35 |   0.3708 |    0.3145 |    0.4518 |     197
curiosity       |      0.30 |   0.4805 |    0.3610 |    0.7182 |     291
desire          |      0.50 |   0.2994 |    0.3906 |    0.2427 |     103
disappointment  |      0.35 |   0.2306 |    0.2500 |    0.2140 |     257
disapproval     |      0.30 |   0.3370 |    0.2773 |    0.4295 |     319
disgust         |      0.45 |   0.3128 |    0.3762 |    0.2676 |     142
embarrassment   |      0.50 |   0.2772 |    0.4118 |    0.2090 |      67
excitement      |      0.30 |   0.2667 |    0.1875 |    0.4615 |     156
fear            |      0.50 |   0.4607 |    0.4184 |    0.5125 |      80
gratitude       |      0.45 |   0.8383 |    0.9137 |    0.7744 |     328
grief           |      0.60 |   0.1714 |    0.1429 |    0.2143 |      14
joy             |      0.40 |   0.3971 |    0.4316 |    0.3677 |     223
love            |      0.40 |   0.6981 |    0.6250 |    0.7906 |     234
nervousness     |      0.50 |   0.2830 |    0.2632 |    0.3061 |      49
optimism        |      0.35 |   0.3962 |    0.4213 |    0.3739 |     222
pride           |      0.40 |   0.1228 |    0.0986 |    0.1628 |      43
realization     |      0.30 |   0.1885 |    0.1898 |    0.1872 |     219
relief          |      0.55 |   0.2333 |    0.2500 |    0.2188 |      32
remorse         |      0.50 |   0.4968 |    0.4286 |    0.5909 |      66
sadness         |      0.40 |   0.3689 |    0.3619 |    0.3762 |     202
surprise        |      0.50 |   0.4373 |    0.4841 |    0.3987 |     153
neutral         |      0.20 |   0.5473 |    0.4321 |    0.7463 |    1549
================================================================================

In [23]:
# Compare fixed threshold (0.5) vs optimized thresholds
test_preds_fixed = (test_probas > 0.5).astype(int)

f1_macro_fixed = f1_score(test_labels, test_preds_fixed, average='macro', zero_division=0)
f1_micro_fixed = f1_score(test_labels, test_preds_fixed, average='micro', zero_division=0)
precision_fixed = precision_score(test_labels, test_preds_fixed, average='macro', zero_division=0)
recall_fixed = recall_score(test_labels, test_preds_fixed, average='macro', zero_division=0)

print("\n" + "=" * 80)
print("COMPARISON: Fixed Threshold (0.5) vs Optimized Per-Emotion Thresholds")
print("=" * 80)
print(f"\n{'Metric':<20} | {'Fixed (0.5)':>12} | {'Optimized':>12} | {'Improvement':>12}")
print("-" * 80)
print(f"{'F1-macro':<20} | {f1_macro_fixed:>12.4f} | {f1_macro_optimized:>12.4f} | {((f1_macro_optimized - f1_macro_fixed) / f1_macro_fixed * 100):>11.1f}%")
print(f"{'F1-micro':<20} | {f1_micro_fixed:>12.4f} | {f1_micro_optimized:>12.4f} | {((f1_micro_optimized - f1_micro_fixed) / f1_micro_fixed * 100):>11.1f}%")
print(f"{'Precision (macro)':<20} | {precision_fixed:>12.4f} | {precision_optimized:>12.4f} | {((precision_optimized - precision_fixed) / precision_fixed * 100):>11.1f}%")
print(f"{'Recall (macro)':<20} | {recall_fixed:>12.4f} | {recall_optimized:>12.4f} | {((recall_optimized - recall_fixed) / recall_fixed * 100):>11.1f}%")
print("=" * 80)

print(f"\n✓ Threshold optimization complete!")
print(f"✓ F1-macro improved from {f1_macro_fixed:.4f} to {f1_macro_optimized:.4f}")
print(f"✓ Optimal thresholds saved to: {thresholds_file}")

================================================================================
COMPARISON: Fixed Threshold (0.5) vs Optimized Per-Emotion Thresholds
================================================================================

Metric               |  Fixed (0.5) |    Optimized |  Improvement
--------------------------------------------------------------------------------
F1-macro             |       0.2740 |       0.3818 |        39.3%
F1-micro             |       0.2701 |       0.4456 |        65.0%
Precision (macro)    |       0.4549 |       0.3677 |       -19.2%
Recall (macro)       |       0.2463 |       0.4212 |        71.0%
================================================================================

✓ Threshold optimization complete!
✓ F1-macro improved from 0.2740 to 0.3818
✓ Optimal thresholds saved to: /content/drive/MyDrive/mental_health_research_V2/models/mental_bert_goemotions/mental_bert_finetuned_20251118_162109/optimal_thresholds.json

# SAVE MODEL

In [24]:
# Save model
trainer.save_model(str(final_model_dir))
tokenizer.save_pretrained(str(final_model_dir))

print(f"Model saved to: {final_model_dir}")

Model saved to: /content/drive/MyDrive/mental_health_research_V2/models/mental_bert_goemotions/mental_bert_finetuned_20251118_162109

In [25]:
# Save metadata
metadata = {
    'model_name': model_name,
    'timestamp': timestamp,
    'num_labels': num_labels,
    'emotion_labels': emotion_labels,
    'train_samples': len(train_dataset),
    'val_samples': len(val_dataset),
    'test_samples': len(test_dataset),
    'validation_results': val_results,
    'test_results': test_results
}

with open(final_model_dir / "metadata.json", 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"\nFINE-TUNING COMPLETE!")
print(f"Test F1 (micro): {test_results['eval_f1_micro']:.4f}")
print(f"Test F1 (macro): {test_results['eval_f1_macro']:.4f}")

FINE-TUNING COMPLETE!
Test F1 (micro): 0.2701
Test F1 (macro): 0.2740