# SETUP

In [1]:
from google.colab import drive
drive.mount('/content/drive')

!pip install -q transformers datasets torch scikit-learn accelerate evaluate tqdm

import json
import pandas as pd
import numpy as np
import torch
from pathlib import Path
from datetime import datetime
from tqdm import tqdm
from sklearn.metrics import f1_score, precision_score, recall_score
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
from datasets import Dataset
from huggingface_hub import login

login(token="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")

BASE_DIR = Path("/content/drive/MyDrive/mental_health_research_V2")
DATA_DIR = BASE_DIR / "data" / "processed" / "go_emotions"
MODEL_DIR = BASE_DIR / "models" / "mental_roberta_goemotions"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Mounted at /content/drive
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.4 MB/s eta 0:00:00
Device: cuda

# DATA PREPARATION

In [2]:
# Load dataset
data_files = sorted(DATA_DIR.glob("go_emotions_raw_*.json"))
data_file = data_files[-1]

with open(data_file, 'r') as f:
    data = json.load(f)

df = pd.DataFrame(data)
print(f"Loaded: {data_file.name}")
print(f"Total samples: {len(df):,}")
print(f"\nSplit distribution:")
print(df['split'].value_counts())

Loaded: go_emotions_raw_20251118_154517.json
Total samples: 57,732

Split distribution:
split
train         46185
test           5774
validation     5773
Name: count, dtype: int64

In [3]:
# GoEmotions has 28 emotion labels (27 emotions + 1 neutral)
emotion_labels = [
    'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
    'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment',
    'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness',
    'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral'
]

num_labels = len(emotion_labels)
print(f"Number of emotion labels: {num_labels}")
print(f"Labels: {emotion_labels}")

Number of emotion labels: 28
Labels: ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']

In [4]:
def labels_to_multihot(labels, num_labels=28):
    multihot = np.zeros(num_labels, dtype=np.float32)
    for label in labels:
        multihot[label] = 1.0
    return multihot

df['labels_multihot'] = df['labels'].apply(lambda x: labels_to_multihot(x, num_labels))

In [5]:
# Split data
train_df = df[df['split'] == 'train'].reset_index(drop=True)
val_df = df[df['split'] == 'validation'].reset_index(drop=True)
test_df = df[df['split'] == 'test'].reset_index(drop=True)

print(f"Train: {len(train_df):,}")
print(f"Validation: {len(val_df):,}")
print(f"Test: {len(test_df):,}")

Train: 46,185
Validation: 5,773
Test: 5,774

In [6]:
model_name = "mental/mental-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/327 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [7]:
# Tokenize datasets
def tokenize_function(examples):
    return tokenizer(
        examples['text'],
        truncation=True,
        padding='max_length',
        max_length=128
    )

# Convert to Dataset format
train_dataset = Dataset.from_pandas(train_df[['text', 'labels_multihot']])
val_dataset = Dataset.from_pandas(val_df[['text', 'labels_multihot']])
test_dataset = Dataset.from_pandas(test_df[['text', 'labels_multihot']])

# Tokenize
train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# Rename labels
train_dataset = train_dataset.rename_column('labels_multihot', 'labels')
val_dataset = val_dataset.rename_column('labels_multihot', 'labels')
test_dataset = test_dataset.rename_column('labels_multihot', 'labels')

# Set format
train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
val_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])

print(f"Datasets ready - Train: {len(train_dataset)}, Val: {len(val_dataset)}, Test: {len(test_dataset)}")

Map:   0%|          | 0/46185 [00:00<?, ? examples/s]

Map:   0%|          | 0/5773 [00:00<?, ? examples/s]

Map:   0%|          | 0/5774 [00:00<?, ? examples/s]

Datasets ready - Train: 46185, Val: 5773, Test: 5774

# MODEL CONFIGURATION

In [8]:
# Load model
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    problem_type="multi_label_classification"
)

model.to(device)
print(f"Model loaded: {model_name}")
print(f"Parameters: {model.num_parameters():,}")

config.json:   0%|          | 0.00/682 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model loaded: mental/mental-roberta-base
Parameters: 124,667,164

In [9]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(predictions))
    y_pred = (probs > 0.5).int().numpy()
    y_true = labels

    return {
        'f1_micro': f1_score(y_true, y_pred, average='micro'),
        'f1_macro': f1_score(y_true, y_pred, average='macro'),
        'precision': precision_score(y_true, y_pred, average='micro'),
        'recall': recall_score(y_true, y_pred, average='micro')
    }

In [10]:
# Load class weights
weights_file = DATA_DIR / "class_weights.json"
with open(weights_file, 'r') as f:
    class_weights_dict = json.load(f)

pos_weight = torch.tensor([class_weights_dict[label] for label in emotion_labels], dtype=torch.float32).to(device)

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

# HYPERPARAMETER OPTIMIZATION

In [11]:
!pip install -q optuna

import optuna

def objective(trial):
    lr = trial.suggest_float('learning_rate', 1e-5, 5e-5, log=True)
    batch_size = trial.suggest_categorical('batch_size', [128, 256, 512])
    gamma = trial.suggest_float('focal_gamma', 1.0, 2.5)
    alpha = trial.suggest_float('focal_alpha', 0.25, 1.0)

    trial_args = TrainingArguments(
        output_dir=str(MODEL_DIR / f"trial_{trial.number}"),
        num_train_epochs=3,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=512,
        learning_rate=lr,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="no",
        warmup_steps=500,
        fp16=True,
        report_to="none"
    )

    trial_pos_weight = pos_weight.clone()

    class TrialFocalLoss(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.alpha = alpha
            self.gamma = gamma

        def forward(self, inputs, targets):
            bce_loss = torch.nn.functional.binary_cross_entropy_with_logits(
                inputs, targets, pos_weight=trial_pos_weight, reduction='none'
            )
            probs = torch.sigmoid(inputs)
            pt = torch.where(targets == 1, probs, 1 - probs)
            focal_weight = (1 - pt) ** self.gamma
            loss = self.alpha * focal_weight * bce_loss
            return loss.mean()

    class TrialTrainer(Trainer):
        def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
            labels = inputs.pop("labels")
            outputs = model(**inputs)
            logits = outputs.logits
            loss = TrialFocalLoss()(logits, labels)
            return (loss, outputs) if return_outputs else loss

    trial_model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
        problem_type="multi_label_classification"
    ).to(device)

    trainer = TrialTrainer(
        model=trial_model,
        args=trial_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics
    )

    trainer.train()
    eval_result = trainer.evaluate()

    del trial_model
    torch.cuda.empty_cache()

    return eval_result['eval_f1_macro']

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

print(f"\nBest F1-macro: {study.best_value:.4f}")
print(f"Best hyperparameters:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

best_lr = study.best_params['learning_rate']
best_batch_size = study.best_params['batch_size']
best_gamma = study.best_params['focal_gamma']
best_alpha = study.best_params['focal_alpha']

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 17.0 MB/s eta 0:00:00

[I 2025-11-18 16:38:28,756] A new study created in memory with name: no-name-31f08c6f-9ddb-4594-9c0f-2c15c59edf75
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:40:16,544] Trial 0 finished with value: 0.26326101890664333 and parameters: {'learning_rate': 3.434774244963202e-05, 'batch_size': 128, 'focal_gamma': 1.3841261366011994, 'focal_alpha': 0.8123320666979923}. Best is trial 0 with value: 0.26326101890664333.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:42:02,653] Trial 1 finished with value: 0.2557335116662275 and parameters: {'learning_rate': 2.3274357581077546e-05, 'batch_size': 128, 'focal_gamma': 1.7604577336952254, 'focal_alpha': 0.6770777189322115}. Best is trial 0 with value: 0.26326101890664333.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:43:48,696] Trial 2 finished with value: 0.2680624032564287 and parameters: {'learning_rate': 3.299767402078938e-05, 'batch_size': 128, 'focal_gamma': 1.8874387881817656, 'focal_alpha': 0.7612377137071633}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:45:34,681] Trial 3 finished with value: 0.2534277919430005 and parameters: {'learning_rate': 2.9755987349620424e-05, 'batch_size': 128, 'focal_gamma': 1.2021426605887129, 'focal_alpha': 0.8182947881052546}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:47:20,753] Trial 4 finished with value: 0.21537801362313608 and parameters: {'learning_rate': 1.2988820953618122e-05, 'batch_size': 128, 'focal_gamma': 1.8477755711947337, 'focal_alpha': 0.8497912923422379}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:48:56,668] Trial 5 finished with value: 0.17182649891060908 and parameters: {'learning_rate': 2.31593438180882e-05, 'batch_size': 256, 'focal_gamma': 1.4298708512421623, 'focal_alpha': 0.868482472995248}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:50:32,961] Trial 6 finished with value: 0.1496820243176793 and parameters: {'learning_rate': 2.365237867150016e-05, 'batch_size': 256, 'focal_gamma': 1.2057631343754467, 'focal_alpha': 0.9977803648799464}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:52:03,149] Trial 7 finished with value: 0.018229166666666668 and parameters: {'learning_rate': 2.501168778796525e-05, 'batch_size': 512, 'focal_gamma': 2.0108804467689185, 'focal_alpha': 0.564198943302428}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:53:49,518] Trial 8 finished with value: 0.1599420365350924 and parameters: {'learning_rate': 1.2601738528046071e-05, 'batch_size': 128, 'focal_gamma': 1.2998000473683233, 'focal_alpha': 0.5026079212517018}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2025-11-18 16:55:19,820] Trial 9 finished with value: 0.0 and parameters: {'learning_rate': 1.103490429625486e-05, 'batch_size': 512, 'focal_gamma': 1.2415847372016378, 'focal_alpha': 0.7231054465745669}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 16:56:56,050] Trial 10 finished with value: 0.25123022395372374 and parameters: {'learning_rate': 4.980794806754809e-05, 'batch_size': 256, 'focal_gamma': 2.3874148412508402, 'focal_alpha': 0.27849631373317085}. Best is trial 2 with value: 0.2680624032564287.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 16:58:42,352] Trial 11 finished with value: 0.276498059873625 and parameters: {'learning_rate': 4.0953246811269324e-05, 'batch_size': 128, 'focal_gamma': 1.5426075275626114, 'focal_alpha': 0.9628986896955554}. Best is trial 11 with value: 0.276498059873625.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 17:00:29,021] Trial 12 finished with value: 0.28352606002999714 and parameters: {'learning_rate': 4.6841105030527245e-05, 'batch_size': 128, 'focal_gamma': 2.1631754123588034, 'focal_alpha': 0.9344799615224688}. Best is trial 12 with value: 0.28352606002999714.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 17:02:15,751] Trial 13 finished with value: 0.2839272392682213 and parameters: {'learning_rate': 4.984509266399202e-05, 'batch_size': 128, 'focal_gamma': 2.24332213529894, 'focal_alpha': 0.9945214122544481}. Best is trial 13 with value: 0.2839272392682213.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 17:04:02,595] Trial 14 finished with value: 0.2829137524058527 and parameters: {'learning_rate': 4.9266388938596294e-05, 'batch_size': 128, 'focal_gamma': 2.2697876843409244, 'focal_alpha': 0.9320285089999578}. Best is trial 13 with value: 0.2839272392682213.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2025-11-18 17:05:32,753] Trial 15 finished with value: 0.0 and parameters: {'learning_rate': 1.6513619231305097e-05, 'batch_size': 512, 'focal_gamma': 2.1789653724485047, 'focal_alpha': 0.43945434479691564}. Best is trial 13 with value: 0.2839272392682213.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 17:07:19,516] Trial 16 finished with value: 0.2817820790169817 and parameters: {'learning_rate': 4.0767697941892016e-05, 'batch_size': 128, 'focal_gamma': 2.4317805494334497, 'focal_alpha': 0.8983336175348677}. Best is trial 13 with value: 0.2839272392682213.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-11-18 17:09:06,247] Trial 17 finished with value: 0.24345226151699448 and parameters: {'learning_rate': 1.6769743635535692e-05, 'batch_size': 128, 'focal_gamma': 2.103521086054175, 'focal_alpha': 0.995490226894292}. Best is trial 13 with value: 0.2839272392682213.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 17:10:42,631] Trial 18 finished with value: 0.24039958322627888 and parameters: {'learning_rate': 4.047615916665056e-05, 'batch_size': 256, 'focal_gamma': 1.6356695803384818, 'focal_alpha': 0.6220183276373896}. Best is trial 13 with value: 0.2839272392682213.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2025-11-18 17:12:12,978] Trial 19 finished with value: 0.037461996157648336 and parameters: {'learning_rate': 2.9438696478693357e-05, 'batch_size': 512, 'focal_gamma': 1.9730771130329268, 'focal_alpha': 0.36000474146867806}. Best is trial 13 with value: 0.2839272392682213.

Best F1-macro: 0.2839
Best hyperparameters:
  learning_rate: 4.984509266399202e-05
  batch_size: 128
  focal_gamma: 2.24332213529894
  focal_alpha: 0.9945214122544481

# TRAINING

In [12]:
# Create final training args with optimized hyperparameters
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_dir = MODEL_DIR / f"checkpoint_{timestamp}"
final_model_dir = MODEL_DIR / f"mental_roberta_finetuned_{timestamp}"

final_training_args = TrainingArguments(
    output_dir=str(output_dir),
    num_train_epochs=3,
    per_device_train_batch_size=best_batch_size if 'best_batch_size' in dir() else 256,
    per_device_eval_batch_size=512,
    learning_rate=best_lr if 'best_lr' in dir() else 2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_micro",
    logging_steps=100,
    warmup_steps=500,
    fp16=True,
    save_total_limit=2,
    report_to="none"
)

# Initialize Trainer with optimized Focal Loss
final_alpha = best_alpha if 'best_alpha' in dir() else 1.0
final_gamma = best_gamma if 'best_gamma' in dir() else 2.0

class FinalFocalLoss(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.alpha = final_alpha
        self.gamma = final_gamma
        self.pos_weight = pos_weight

    def forward(self, inputs, targets):
        bce_loss = torch.nn.functional.binary_cross_entropy_with_logits(
            inputs, targets, pos_weight=self.pos_weight, reduction='none'
        )
        probs = torch.sigmoid(inputs)
        pt = torch.where(targets == 1, probs, 1 - probs)
        focal_weight = (1 - pt) ** self.gamma
        loss = self.alpha * focal_weight * bce_loss
        return loss.mean()

class FinalTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss = FinalFocalLoss()(logits, labels)
        return (loss, outputs) if return_outputs else loss

trainer = FinalTrainer(
    model=model,
    args=final_training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

/tmp/ipython-input-3575852466.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `FinalTrainer.__init__`. Use `processing_class` instead.
  trainer = FinalTrainer(

In [13]:
# Train with optimized hyperparameters
train_result = trainer.train()

print(f"\nTraining complete - Time: {train_result.metrics['train_runtime']:.2f}s")

Training complete - Time: 131.49s

# EVALUATION

In [14]:
# Evaluate on validation
val_results = trainer.evaluate()

print("Validation Results:")
for key, value in val_results.items():
    print(f"{key}: {value:.4f}")

Validation Results:
eval_loss: 0.0267
eval_f1_micro: 0.2796
eval_f1_macro: 0.2796
eval_precision: 0.5403
eval_recall: 0.1886
eval_runtime: 1.8698
eval_samples_per_second: 3087.4210
eval_steps_per_second: 6.4180
epoch: 3.0000

In [15]:
# Evaluate on test
test_results = trainer.evaluate(test_dataset)

print("Test Results:")
for key, value in test_results.items():
    print(f"{key}: {value:.4f}")

Test Results:
eval_loss: 0.0266
eval_f1_micro: 0.2745
eval_f1_macro: 0.2757
eval_precision: 0.5427
eval_recall: 0.1837
eval_runtime: 1.8270
eval_samples_per_second: 3160.3390
eval_steps_per_second: 6.5680
epoch: 3.0000

In [16]:
# Per-emotion scores with fixed threshold (0.5)
test_predictions = trainer.predict(test_dataset)
sigmoid = torch.nn.Sigmoid()
probs = sigmoid(torch.Tensor(test_predictions.predictions))
pred_labels = (probs > 0.5).int().numpy()

print("\nPer-Emotion F1 Scores (Fixed Threshold 0.5):")
for i, emotion in enumerate(emotion_labels):
    f1 = f1_score(test_predictions.label_ids[:, i], pred_labels[:, i], zero_division=0)
    print(f"{emotion:15s}: {f1:.4f}")

Per-Emotion F1 Scores (Fixed Threshold 0.5):
admiration     : 0.4197
amusement      : 0.5819
anger          : 0.2626
annoyance      : 0.0000
approval       : 0.0237
caring         : 0.3145
confusion      : 0.2109
curiosity      : 0.1491
desire         : 0.3051
disappointment : 0.0078
disapproval    : 0.0756
disgust        : 0.2696
embarrassment  : 0.3019
excitement     : 0.2222
fear           : 0.4599
gratitude      : 0.8353
grief          : 0.1587
joy            : 0.2585
love           : 0.6695
nervousness    : 0.2393
optimism       : 0.3098
pride          : 0.2029
realization    : 0.0091
relief         : 0.1887
remorse        : 0.4969
sadness        : 0.3478
surprise       : 0.4000
neutral        : 0.0000

# THRESHOLD OPTIMIZATION

In [17]:
# Get validation predictions (probabilities)
val_predictions = trainer.predict(val_dataset)
val_probas = torch.sigmoid(torch.Tensor(val_predictions.predictions)).numpy()
val_labels = val_predictions.label_ids

print(f"Validation probabilities shape: {val_probas.shape}")
print(f"Validation labels shape: {val_labels.shape}")

Validation probabilities shape: (5773, 28)
Validation labels shape: (5773, 28)

In [18]:
# Grid search for optimal thresholds per emotion
threshold_results = {}

print("Running grid search for optimal thresholds...")
for t in tqdm(range(5, 100, 5), desc="Testing thresholds"):
    threshold = t / 100
    threshold_results[threshold] = []

    for label_idx, emotion in enumerate(emotion_labels):
        y_true = val_labels[:, label_idx]
        y_pred = (val_probas[:, label_idx] > threshold).astype(int)

        f1 = f1_score(y_true, y_pred, zero_division=0)
        precision = precision_score(y_true, y_pred, zero_division=0)
        recall = recall_score(y_true, y_pred, zero_division=0)
        support = y_true.sum()

        threshold_results[threshold].append({
            'emotion': emotion,
            'threshold': threshold,
            'f1': f1,
            'precision': precision,
            'recall': recall,
            'support': support
        })

print(f"Grid search complete! Tested {len(threshold_results)} thresholds for {len(emotion_labels)} emotions.")

Running grid search for optimal thresholds...

Testing thresholds: 100%|██████████| 19/19 [00:03<00:00,  4.89it/s]

Grid search complete! Tested 19 thresholds for 28 emotions.

In [19]:
# Find best threshold for each emotion
best_thresholds = {}
best_metrics = []

for emotion in emotion_labels:
    best_f1 = -1
    best_result = None

    for threshold, results in threshold_results.items():
        for result in results:
            if result['emotion'] == emotion and result['f1'] > best_f1:
                best_f1 = result['f1']
                best_result = result

    best_thresholds[emotion] = best_result['threshold']
    best_metrics.append(best_result)

# Display optimal thresholds
print("Optimal Thresholds per Emotion:")
print("=" * 60)
for metric in sorted(best_metrics, key=lambda x: x['support'], reverse=True):
    print(f"{metric['emotion']:15s} | Threshold: {metric['threshold']:.2f} | F1: {metric['f1']:.4f} | Support: {int(metric['support']):>4}")

print(f"\nAverage optimal threshold: {np.mean(list(best_thresholds.values())):.3f}")

Optimal Thresholds per Emotion:
============================================================
neutral         | Threshold: 0.25 | F1: 0.5461 | Support: 1547
approval        | Threshold: 0.30 | F1: 0.2745 | Support:  475
admiration      | Threshold: 0.35 | F1: 0.6064 | Support:  458
annoyance       | Threshold: 0.35 | F1: 0.2950 | Support:  352
disapproval     | Threshold: 0.30 | F1: 0.2999 | Support:  315
curiosity       | Threshold: 0.35 | F1: 0.5061 | Support:  311
gratitude       | Threshold: 0.45 | F1: 0.7979 | Support:  302
amusement       | Threshold: 0.40 | F1: 0.6686 | Support:  287
optimism        | Threshold: 0.35 | F1: 0.4505 | Support:  274
realization     | Threshold: 0.30 | F1: 0.2029 | Support:  234
anger           | Threshold: 0.40 | F1: 0.4185 | Support:  231
joy             | Threshold: 0.40 | F1: 0.4840 | Support:  223
love            | Threshold: 0.40 | F1: 0.6514 | Support:  220
disappointment  | Threshold: 0.35 | F1: 0.2519 | Support:  208
confusion       | Threshold: 0.40 | F1: 0.3410 | Support:  190
sadness         | Threshold: 0.40 | F1: 0.4168 | Support:  185
excitement      | Threshold: 0.35 | F1: 0.2764 | Support:  156
surprise        | Threshold: 0.45 | F1: 0.4727 | Support:  154
caring          | Threshold: 0.35 | F1: 0.3173 | Support:  153
disgust         | Threshold: 0.45 | F1: 0.3000 | Support:  135
desire          | Threshold: 0.45 | F1: 0.3689 | Support:   97
fear            | Threshold: 0.50 | F1: 0.4516 | Support:   87
remorse         | Threshold: 0.45 | F1: 0.5751 | Support:   87
embarrassment   | Threshold: 0.60 | F1: 0.2796 | Support:   71
nervousness     | Threshold: 0.55 | F1: 0.2921 | Support:   51
relief          | Threshold: 0.45 | F1: 0.2837 | Support:   44
pride           | Threshold: 0.45 | F1: 0.1299 | Support:   35
grief           | Threshold: 0.65 | F1: 0.3704 | Support:   15

Average optimal threshold: 0.409

In [20]:
# Save optimal thresholds
final_model_dir.mkdir(parents=True, exist_ok=True)
thresholds_file = final_model_dir / "optimal_thresholds.json"
with open(thresholds_file, 'w') as f:
    json.dump(best_thresholds, f, indent=2)

print(f"Optimal thresholds saved to: {thresholds_file}")

Optimal thresholds saved to: /content/drive/MyDrive/mental_health_research_V2/models/mental_roberta_goemotions/mental_roberta_finetuned_20251118_171212/optimal_thresholds.json

In [21]:
# Evaluate on test set with optimized thresholds
test_probas = torch.sigmoid(torch.Tensor(test_predictions.predictions)).numpy()
test_labels = test_predictions.label_ids

# Apply per-emotion optimal thresholds
test_preds_optimized = np.zeros_like(test_probas, dtype=int)
for label_idx, emotion in enumerate(emotion_labels):
    threshold = best_thresholds[emotion]
    test_preds_optimized[:, label_idx] = (test_probas[:, label_idx] > threshold).astype(int)

# Calculate metrics with optimized thresholds
f1_macro_optimized = f1_score(test_labels, test_preds_optimized, average='macro', zero_division=0)
f1_micro_optimized = f1_score(test_labels, test_preds_optimized, average='micro', zero_division=0)
precision_optimized = precision_score(test_labels, test_preds_optimized, average='macro', zero_division=0)
recall_optimized = recall_score(test_labels, test_preds_optimized, average='macro', zero_division=0)

print("Test Results with Optimized Thresholds:")
print("=" * 60)
print(f"F1-macro:  {f1_macro_optimized:.4f}")
print(f"F1-micro:  {f1_micro_optimized:.4f}")
print(f"Precision: {precision_optimized:.4f}")
print(f"Recall:    {recall_optimized:.4f}")

Test Results with Optimized Thresholds:
============================================================
F1-macro:  0.3717
F1-micro:  0.4301
Precision: 0.3428
Recall:    0.4409

In [22]:
# Per-emotion scores with optimized thresholds
print("\nPer-Emotion F1 Scores (Optimized Thresholds):")
print("=" * 80)
print(f"{'Emotion':<15} | {'Threshold':>9} | {'F1':>8} | {'Precision':>9} | {'Recall':>9} | {'Support':>7}")
print("-" * 80)

optimized_emotion_metrics = []
for i, emotion in enumerate(emotion_labels):
    y_true = test_labels[:, i]
    y_pred = test_preds_optimized[:, i]

    f1 = f1_score(y_true, y_pred, zero_division=0)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    support = y_true.sum()
    threshold = best_thresholds[emotion]

    optimized_emotion_metrics.append({
        'emotion': emotion,
        'threshold': threshold,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'support': support
    })

    print(f"{emotion:<15} | {threshold:>9.2f} | {f1:>8.4f} | {precision:>9.4f} | {recall:>9.4f} | {int(support):>7}")

print("=" * 80)

Per-Emotion F1 Scores (Optimized Thresholds):
================================================================================
Emotion         | Threshold |       F1 | Precision |    Recall | Support
--------------------------------------------------------------------------------
admiration      |      0.35 |   0.5685 |    0.5414 |    0.5984 |     503
amusement       |      0.40 |   0.6154 |    0.5134 |    0.7680 |     250
anger           |      0.40 |   0.3943 |    0.3516 |    0.4486 |     214
annoyance       |      0.35 |   0.2709 |    0.2629 |    0.2795 |     347
approval        |      0.30 |   0.2938 |    0.2563 |    0.3440 |     500
caring          |      0.35 |   0.3430 |    0.2602 |    0.5030 |     165
confusion       |      0.40 |   0.3185 |    0.2957 |    0.3452 |     197
curiosity       |      0.35 |   0.4835 |    0.3750 |    0.6804 |     291
desire          |      0.45 |   0.3223 |    0.3148 |    0.3301 |     103
disappointment  |      0.35 |   0.2400 |    0.2170 |    0.2685 |     257
disapproval     |      0.30 |   0.3074 |    0.2140 |    0.5455 |     319
disgust         |      0.45 |   0.2715 |    0.2562 |    0.2887 |     142
embarrassment   |      0.60 |   0.2727 |    0.5714 |    0.1791 |      67
excitement      |      0.35 |   0.2636 |    0.1957 |    0.4038 |     156
fear            |      0.50 |   0.4599 |    0.4019 |    0.5375 |      80
gratitude       |      0.45 |   0.8333 |    0.8979 |    0.7774 |     328
grief           |      0.65 |   0.0800 |    0.0909 |    0.0714 |      14
joy             |      0.40 |   0.4027 |    0.3974 |    0.4081 |     223
love            |      0.40 |   0.6772 |    0.5744 |    0.8248 |     234
nervousness     |      0.55 |   0.2353 |    0.2778 |    0.2041 |      49
optimism        |      0.35 |   0.3810 |    0.3525 |    0.4144 |     222
pride           |      0.45 |   0.2093 |    0.2093 |    0.2093 |      43
realization     |      0.30 |   0.2087 |    0.1484 |    0.3516 |     219
relief          |      0.45 |   0.1791 |    0.1176 |    0.3750 |      32
remorse         |      0.45 |   0.4607 |    0.3661 |    0.6212 |      66
sadness         |      0.40 |   0.3659 |    0.3103 |    0.4455 |     202
surprise        |      0.45 |   0.4169 |    0.3876 |    0.4510 |     153
neutral         |      0.25 |   0.5332 |    0.4419 |    0.6720 |    1549
================================================================================

In [23]:
# Compare fixed threshold (0.5) vs optimized thresholds
test_preds_fixed = (test_probas > 0.5).astype(int)

f1_macro_fixed = f1_score(test_labels, test_preds_fixed, average='macro', zero_division=0)
f1_micro_fixed = f1_score(test_labels, test_preds_fixed, average='micro', zero_division=0)
precision_fixed = precision_score(test_labels, test_preds_fixed, average='macro', zero_division=0)
recall_fixed = recall_score(test_labels, test_preds_fixed, average='macro', zero_division=0)

print("\n" + "=" * 80)
print("COMPARISON: Fixed Threshold (0.5) vs Optimized Per-Emotion Thresholds")
print("=" * 80)
print(f"\n{'Metric':<20} | {'Fixed (0.5)':>12} | {'Optimized':>12} | {'Improvement':>12}")
print("-" * 80)
print(f"{'F1-macro':<20} | {f1_macro_fixed:>12.4f} | {f1_macro_optimized:>12.4f} | {((f1_macro_optimized - f1_macro_fixed) / f1_macro_fixed * 100):>11.1f}%")
print(f"{'F1-micro':<20} | {f1_micro_fixed:>12.4f} | {f1_micro_optimized:>12.4f} | {((f1_micro_optimized - f1_micro_fixed) / f1_micro_fixed * 100):>11.1f}%")
print(f"{'Precision (macro)':<20} | {precision_fixed:>12.4f} | {precision_optimized:>12.4f} | {((precision_optimized - precision_fixed) / precision_fixed * 100):>11.1f}%")
print(f"{'Recall (macro)':<20} | {recall_fixed:>12.4f} | {recall_optimized:>12.4f} | {((recall_optimized - recall_fixed) / recall_fixed * 100):>11.1f}%")
print("=" * 80)

print(f"\n✓ Threshold optimization complete!")
print(f"✓ F1-macro improved from {f1_macro_fixed:.4f} to {f1_macro_optimized:.4f}")
print(f"✓ Optimal thresholds saved to: {thresholds_file}")

================================================================================
COMPARISON: Fixed Threshold (0.5) vs Optimized Per-Emotion Thresholds
================================================================================

Metric               |  Fixed (0.5) |    Optimized |  Improvement
--------------------------------------------------------------------------------
F1-macro             |       0.2757 |       0.3717 |        34.8%
F1-micro             |       0.2745 |       0.4301 |        56.7%
Precision (macro)    |       0.4850 |       0.3428 |       -29.3%
Recall (macro)       |       0.2569 |       0.4409 |        71.6%
================================================================================

✓ Threshold optimization complete!
✓ F1-macro improved from 0.2757 to 0.3717
✓ Optimal thresholds saved to: /content/drive/MyDrive/mental_health_research_V2/models/mental_roberta_goemotions/mental_roberta_finetuned_20251118_171212/optimal_thresholds.json

# SAVE MODEL

In [24]:
# Save model
trainer.save_model(str(final_model_dir))
tokenizer.save_pretrained(str(final_model_dir))

print(f"Model saved to: {final_model_dir}")

Model saved to: /content/drive/MyDrive/mental_health_research_V2/models/mental_roberta_goemotions/mental_roberta_finetuned_20251118_171212

In [25]:
# Save metadata
metadata = {
    'model_name': model_name,
    'timestamp': timestamp,
    'num_labels': num_labels,
    'emotion_labels': emotion_labels,
    'train_samples': len(train_dataset),
    'val_samples': len(val_dataset),
    'test_samples': len(test_dataset),
    'validation_results': val_results,
    'test_results': test_results
}

with open(final_model_dir / "metadata.json", 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"\nFINE-TUNING COMPLETE!")
print(f"Test F1 (micro): {test_results['eval_f1_micro']:.4f}")
print(f"Test F1 (macro): {test_results['eval_f1_macro']:.4f}")

FINE-TUNING COMPLETE!
Test F1 (micro): 0.2745
Test F1 (macro): 0.2757